### ISSUE TITLE
create a script to provide "diff" summary between two different dates (or just commits)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-usage-dashboard#20]
For reporting purposes it would be useful to be able to tell the "diff" between two points in time. Well -- could be just two commits (but best to allow specification of from/to dates). `git diff` by itself is hard to digest to get 'numbers'.

So some tool with `FROM [TO]` arguments, with `TO` being now (last commit) if not specified. Both could be a commitish or a date (typically need to just a date, e.g. 2021/11/18 for today).

I think the implementation could be just:
- take (only) all newly added datasets between `from` and `to` dates
- produce exactly the same as what output produced into current README.md 

That should give us an idea on what datasets (with what properties) were added in e.g. past month or year.

**Comment by jwodder** [comment]
@yarikoptic To be clear, you want the script to examine the history of `datalad-repos.json` in this repository between two points in time and compile a set of READMEs listing only the datasets present in the later `datalad-repos.json`, correct?
