### ISSUE TITLE
Does not list https://github.com/OpenNeuroDatasets-JSONLD

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-usage-dashboard#27]
this organization contains forks from OpenNeuroDatasets. I am not sure why they were not discovered

**Comment by yarikoptic** [comment]
remains the case. may be because those are forks?

**Comment by jwodder** [comment]
@yarikoptic Code search via GitHub's REST API has [various restrictions](https://docs.github.com/en/search-github/searching-on-github/searching-code#considerations-for-code-search), of which the following may be relevant:

> Code in [forks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks) is only searchable if the fork has more stars than the parent repository. Forks with fewer stars than the parent repository are not indexed for code search. To include forks with more stars than their parent in the search results, you will need to add `fork:true` or `fork:only` to your query.

**Comment by candleindark** [comment]
> oh, thank you @jwodder for digging up! I think it would be generally sensible for us to enable search through forks too so to add `fork:true` to the query. It would then facilitate interesting use-case for datalad-registry (attn @candleindark) that we would have multiple URLs, possibly with the same state, for the same dataset UUID.

Many of the repos in `https://github.com/OpenNeuroDatasets-JSONLD` do not have more stars than their parent. I think adding `fork:true` to the query will possibly only give you some of the repos in `https://github.com/OpenNeuroDatasets-JSONLD`. Many of the repos in `https://github.com/OpenNeuroDatasets-JSONLD` have the same number of stars as their parents. It is not clear if those will be included in the result of a query with the `fork:true` option (I guess one has to try to find out).
