### ISSUE TITLE
Add "Last updated"  column in the table(s)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-usage-dashboard#40]
primarily was interested in one for OSF: wanted to checkout the most recent'ish one, but impossible ATM.

For organization groups could be the latest among all repositories under that organization.

That would also harmonize display a bit since then OSF could become a table as well (and thus I could sort it)

**Comment by jwodder** [comment]
@yarikoptic Is this "last updated" field supposed to be when a repository was last updated on GitHub/OSF/GIN or when its entry in `datalad-repos.json` was last updated?

* If it's supposed to be when a repository was updated on GitHub/OSF/GIN, then, for GitHub at least (and possibly one or both of the others; I need to check) should the repository's `updated_at` or `pushed_at` timestamp be recorded?  I don't know what causes `updated_at` to be updated, but the `pushed_at` timestamp for a repository can sometimes be the later of the two; for example, at the moment, for [my repolist repository](https://github.com/jwodder/repolist), the GitHub API reports an `updated_at` timestamp of 2023-11-01T15:33:02Z (two seconds after `created_at`) and a `pushed_at` timestamp of 2024-01-23T18:06:08Z.

**Comment by yarikoptic** [comment]
for the repository (not our entry).  I guess let's take `pushed_at` for github. Note to myself: that timestamp would be after the date of the actual commit in the repo, so  we indeed would be looking at the "most recently updated" (on the hosting portal) and not necessarily "most recently updated in git" (i.e. could be old commits pushed)
