### ISSUE TITLE
Add "size" to OSF and GIN sources

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-usage-dashboard#45]
GitHub would not know.  I didn't check but I would assume that OSF and/or GIN might provide this metadata in the listing. As we now already have Last-Modified, we would update records anyways so if size is also available, let's add it as well.

Use case which inspired this: I wanted a small'ish and recent'ish OSF datalad dataset to try on. Now need to go through few one at a time (for now just spend half hour troubleshooting why first one didn't clone at all ;-) )

**Comment by jwodder** [comment]
@yarikoptic

* OSF does not provide sizes.
* Can you link to a GIN repository with git-annexed files for which we can easily judge if the size reported by GIN includes the git-annexed content?  (I assume this concern is why you're excluding GitHub.)

**Comment by yarikoptic** [comment]
eh, sad -- OSF was the main motivation.  For now let's not bother about GIN. If needed I could get it from registry... well, after
- https://github.com/datalad/datalad-registry/issues/302
is fixed ;)
