### ISSUE TITLE
a repo is listed as not a dataset but it is

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-usage-dashboard#6]
https://github.com/maxadam2017/midtermproject  
has https://github.com/maxadam2017/midtermproject/blob/master/.datalad/config (modified 12 months ago)

![image](https://user-images.githubusercontent.com/39889/124318733-18ca3c80-db47-11eb-82c4-dd29560c86b0.png)

I wonder if it just wasn't returned in a search query for `.datalad/config` or may be some code logic needs a tuneup?

**Comment by jwodder** [comment]
@yarikoptic It appears it just wasn't returned by GitHub's search.  Even if you [just search for hits in that user's account](https://github.com/search?q=user%3Amaxadam2017+path%3A.datalad+filename%3Aconfig), you get nothing.  (You do get a hit if you click on the "Repositories" option, but using the search API to search for repositories matching `path:.datalad filename:config` returns nothing, as those qualifiers are only supposed to be used for code searches.)

**Comment by yarikoptic** [comment]
was likely addressed by #18 which is likely the only way to handle "not necessarily complete" search results
