### ISSUE TITLE
Add datasets published on OSF

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-usage-dashboard#7]
@mih @adswa ?

**Comment by mih** [comment]
This seems to be a good way: https://osf.io/search/?q=tags:(%22DataLad%20dataset%22)

**Comment by yarikoptic** [comment]
Cool, thank you @mih. A good number of them.  Since I guess there is no sensible way to group them (like in organizations etc on github), we would just have them all listed under `osf://` group. Some of them might be even published on github as well (wo data if annex) but it would not be for this usage dashboard to identify them (based on .datalad/config:uuid) -- this will be up for the datalad-registry.

Dear @jwodder , would you be kind to extend listing with hits from the OSF under a common `osf://` group.  We will not analyze for any `run` records, just that they are datasets. OSF API is here (https://developer.osf.io/) although on a quick look I found no `search` endpoint.
