### ISSUE TITLE
Make "Gone" more robust?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-usage-dashboard#9]
We have many repos which still exist etc migrating into Gone (and likely back ;), didn't analyze). I guess it is because of github search index gets cleaned up periodically and does not necessarily has all the hits all the time.  Ideally we should mitigate that somehow.  Some ideas

- have a time stamp "last-seen" for each entry and migrate to gone only after e.g. a month
- sense (query) those repos via github api to check if still there etc 

WDYT @jwodder ?

**Comment by jwodder** [comment]
@yarikoptic 

> sense (query) those repos via github api to check if still there etc

Assuming that "Gone" is supposed to list repos that no longer exist rather than repos that were modified/rewritten to no longer use Datalad, this seems like the better option.
